phabricatorUrl: https://phabricator.wikimedia.org/
backlog:
    board: PHID-PROJ-7nmqeeo6pfndicguymjd  # Analytics
    incoming:
          - PHID-PCOL-hhn7svjs5isgzkbexbia  # Incoming
          # - PHID-PCOL-manwotcfobaphb7zh7zw  # Backlog (later)
    active:
          - PHID-PCOL-7gpu4qicbrji6acfdksd  # Operational Excellence
          - PHID-PCOL-3sppqpc2tnojn2j6muhn  # Data Quality
          - PHID-PCOL-xvx5owi7wrgu4dxyh7pm  # Kafka Work
          - PHID-PCOL-btdy5wlrnem72b5dafzo  # Smart Tools for Better Data
          - PHID-PCOL-gkmtdmuskyal3m7npm2r  # Wikistats Beta
          - PHID-PCOL-qo5trpy4ndztso3cmrl6  # Geowiki
          - PHID-PCOL-4td6qmn32r3vbrjh4xm2  # Pageview API
    inactive:
          - PHID-PCOL-e2qq3t23nms72jwqt7lp  # Mentoring
          - PHID-PCOL-mjr3oprjv3ati3lqux53  # Bots
          - PHID-PCOL-ganhiwt4ew3pxrmmdpca  # Modern Event Platform
          - PHID-PCOL-4rv7bii65xd6wxektaka  # Jupyter
          - PHID-PCOL-twmau77mw5cdimydid5w  # Wikistats Production
          - PHID-PCOL-7konzxbwmknvinn6adey  # Dashiki
          - PHID-PCOL-wobo5crhgrxp5smdwswo  # Forgotten documentation
    radar: PHID-PCOL-in3gnye265b7dswnykvk
    deprioritized: PHID-PCOL-kxrnbaiiaopxypm5kfi7
    blocked: PHID-PCOL-q7r5qfcdr4rgbzipnref
    stallConditions:
        unbreak: 7 days static
        high: 7 weeks static
        normal: 7 months static
        low: 7 quarters static
        lowest: 7 years static
kanban:
    board: PHID-PROJ-mseu6whr6z4kqtzmoahl
    parentTasks: PHID-PCOL-6cwxiegnuggy7scjawko
    nextUp: PHID-PCOL-gj52fgl7wdrdkoazrt6z
    paused: PHID-PCOL-zgrbvgurwzhvvh2dkuvp
    inProgress: PHID-PCOL-hn2ehxlwqk6di6ns7nej
    inCodeReview: PHID-PCOL-ixaphm56xqgmiavsrc2w
    readyToDeploy: PHID-PCOL-mau24duehhxrd2p7vcqc
    done: PHID-PCOL-wfre77j5pabc4hedon6j
    stallConditions:
        parentTasks: 2 months inactive
        nextUp: 4 weeks static
        paused: 6 weeks inactive
        inProgress: 2 weeks inactive
        inCodeReview: 2 weeks static
        readyToDeploy: 2 weeks static
users:
    - PHID-USER-a6yycs7vaq2biua4pudd  # elukey
    - PHID-USER-rn7ojj3xjygpzmo7ekex  # fdans
    - PHID-USER-g7bfwahewstu6un6ewf6  # jallemandou
    - PHID-USER-zi2n3djggr2p7i54o5tp  # mforns
    - PHID-USER-vbyvvtbztxaeuaxelxx4  # milimetric
    - PHID-USER-mwkkwzbzlkvdl4w2og44  # nuria
    - PHID-USER-tafngdco2cilcyr7qhhg  # ottomata
dryRun: true
